todo:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/code
    links:
      - postgres

postgres:
  image: postgres
  volumes:
    - /var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
  expose:
    - "5432"
  ports:
    - "5432:5432"
  environment:
      - POSTGRES_PASSWORD=postgres